version: "3"
services:
  yearlyreps:
    image: registry.tompaton.com/tompaton/yearlyreps2
    networks:
      - www
    env_file: production.env
    volumes:
      - ./data/:/data
    restart: unless-stopped

networks:
  www:
    external:
      name: www
