[project]
name = "yearlyreps2"
version = "0.1.0"
description = "yearlyreps.tompaton.com"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mako>=1.3.9",
    "nanodjango>=0.9.2",
]
