# Generated by Django 5.1.6 on 2025-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("goal_id", models.AutoField(primary_key=True, serialize=False)),
                ("goal", models.TextField()),
                ("target", models.IntegerField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "goal",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reps",
            fields=[
                ("rep_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.IntegerField()),
                ("count", models.IntegerField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reps",
                "managed": False,
            },
        ),
    ]
