# Generated by Django 5.1.7 on 2025-03-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("goal_id", models.AutoField(primary_key=True, serialize=False)),
                ("goal", models.TextField()),
                ("target", models.IntegerField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reps",
            fields=[
                ("rep_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("count", models.IntegerField(blank=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.goal"
                    ),
                ),
            ],
        ),
    ]
